### ISSUE TITLE
License? Maven availibility?

### ISSUE THREAD

**Issue by bsungur** [kdefombelle/xmlcompare#5]
Hi @kdefombelle
This xmlcompare looks like a good fit for a project I am working on.
Could you post a license for xmlcompare?
And what would it take to make xmlcompare available via Maven Central?

Thanks,
Brandon

**Comment by kdefombelle** [comment]
Hello @bsungur,
MIT license added. 
Maven central deployment can be considered if interest is confirmed.
Thanks,

**Comment by kdefombelle** [comment]
Snapshots available on [Central Repository Snapshots](https://s01.oss.sonatype.org/index.html#view-repositories;snapshots~browsestorage~/io/github/kdefombelle/xmlcompare-core/1.0-SNAPSHOT/xmlcompare-core-1.0-20211109.145840-2.jar).
You can also browse from [here](https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/kdefombelle/)

**Comment by kdefombelle** [comment]
Kept on snapshots repo as no further interest showed.
